# Generated by Django 5.2.17 on 2026-09-29 09:47

import apps.homework.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_lesson_materials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(default='Uy vazifasi', max_length=200, verbose_name='sarlavha')),
                ('instructions', models.TextField(help_text='Nima qilish va nimani yuborish kerak: kod, rasm, havola yoki fayl.', verbose_name='topshiriq')),
                ('deadline', models.DateTimeField(blank=True, help_text='Ixtiyoriy. Muddatdan keyin ham yuborish mumkin — javob «kechikkan» deb belgilanadi.', null=True, verbose_name='muddat')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='catalog.lesson', verbose_name='dars')),
            ],
            options={
                'verbose_name': 'uy vazifasi',
                'verbose_name_plural': 'uy vazifalari',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('attempt', models.PositiveSmallIntegerField(default=1, verbose_name='urinish')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Tekshirilmoqda'), ('CHANGES_REQUESTED', 'Qayta ishlash kerak'), ('ACCEPTED', 'Qabul qilindi')], db_index=True, default='SUBMITTED', max_length=20, verbose_name='holat')),
                ('text', models.TextField(blank=True, verbose_name='izoh')),
                ('code', models.TextField(blank=True, verbose_name='kod')),
                ('language', models.CharField(blank=True, max_length=20, verbose_name='kod tili')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='havola')),
                ('late', models.BooleanField(default=False, verbose_name='kechikkan')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='baho')),
                ('feedback', models.TextField(blank=True, verbose_name="o'qituvchi izohi")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='tekshirilgan')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.assignment', verbose_name='vazifa')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='tekshirgan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'javob',
                'verbose_name_plural': 'javoblar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=apps.homework.models.submission_path, verbose_name='fayl')),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('size', models.PositiveIntegerField(verbose_name='hajmi (bayt)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='turi')),
                ('is_image', models.BooleanField(default=False, verbose_name='rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yuklangan')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='homework.submission', verbose_name='javob')),
            ],
            options={
                'verbose_name': 'javob fayli',
                'verbose_name_plural': 'javob fayllari',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='homework_su_status_69e54c_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student', 'attempt'), name='unique_submission_attempt'),
        ),
    ]
