# Generated by Django 5.2.17 on 2026-09-29 17:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_lesson_materials'),
        ('learning', '0003_studygroup_meet_url_studygroup_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='boshlanishi')),
                ('duration_min', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='davomiyligi (daqiqa)')),
                ('kind', models.CharField(choices=[('ONLINE', 'Onlayn'), ('OFFLINE', 'Offlayn')], default='ONLINE', max_length=10, verbose_name='shakl')),
                ('meet_url', models.URLField(blank=True, help_text='Onlayn dars uchun.', verbose_name='Meet yoki Zoom havolasi')),
                ('room', models.CharField(blank=True, help_text='Offlayn dars uchun, masalan: 3-xona.', max_length=60, verbose_name='xona')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='sarlavha')),
                ('notes', models.TextField(blank=True, help_text="O'quvchilarga ko'rinadi: nima o'tildi, nima tayyorlash.", verbose_name='izoh')),
                ('recording_url', models.URLField(blank=True, help_text='YouTube (yopiq), Google Drive va h.k.', verbose_name='yozuv havolasi')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='bekor qilingan')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='bekor qilish sababi')),
                ('generated', models.BooleanField(default=False, editable=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_lessons', to='learning.studygroup', verbose_name='guruh')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.lesson', verbose_name='mavzu (dars)')),
            ],
            options={
                'verbose_name': 'jonli dars',
                'verbose_name_plural': 'jonli darslar',
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PRESENT', 'Keldi'), ('LATE', 'Kechikdi'), ('ABSENT', 'Kelmadi'), ('EXCUSED', 'Sababli')], max_length=10, verbose_name='holat')),
                ('joined_at', models.DateTimeField(blank=True, help_text='"Qo\'shilish" bosilgan vaqt.', null=True, verbose_name="qo'shildi")),
                ('marked_at', models.DateTimeField(blank=True, null=True, verbose_name='belgilangan')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='belgiladi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
                ('live_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='live.livelesson', verbose_name='dars')),
            ],
            options={
                'verbose_name': 'davomat',
                'verbose_name_plural': 'davomat',
                'ordering': ('live_lesson', 'student'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='hafta kuni')),
                ('starts_at', models.TimeField(verbose_name='boshlanishi')),
                ('duration_min', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='davomiyligi (daqiqa)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='learning.studygroup', verbose_name='guruh')),
            ],
            options={
                'verbose_name': 'jadvaldagi dars',
                'verbose_name_plural': 'haftalik jadval',
                'ordering': ('weekday', 'starts_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='livelesson',
            constraint=models.UniqueConstraint(fields=('group', 'starts_at'), name='unique_live_lesson_time'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('live_lesson', 'student'), name='unique_attendance'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(fields=('group', 'weekday', 'starts_at'), name='unique_schedule_slot'),
        ),
    ]
