# Generated by Django 5.2.17 on 2026-09-29 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_lesson_materials'),
        ('learning', '0003_studygroup_meet_url_studygroup_room'),
        ('live', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='ochilgan')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_lessons', to='learning.studygroup', verbose_name='guruh')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.lesson', verbose_name='dars')),
                ('live_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered', to='live.livelesson', verbose_name='jonli dars')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim ochdi')),
            ],
            options={
                'verbose_name': "o'tilgan dars",
                'verbose_name_plural': "o'tilgan darslar",
                'ordering': ('-opened_at',),
                'constraints': [models.UniqueConstraint(fields=('group', 'lesson'), name='unique_group_lesson')],
            },
        ),
    ]
