# Generated by Django 5.2.17 on 2026-09-28 05:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_lead_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text="O'chirilsa, saytdagi chat yashiriladi. Telegram bot esa faqat raqam so'rab, ariza qabul qiladi.", verbose_name='saytda yoqilgan')),
                ('knowledge', models.TextField(blank=True, help_text="AI bilishi kerak bo'lgan faktlar: chegirmalar, bo'lib to'lash, sertifikat, sinov darsi, guruhlar jadvali, mo'ljal. AI faqat shu yerda va saytda yozilgan narsani aytadi.", verbose_name="qo'shimcha ma'lumot")),
                ('daily_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text="Tugasa, AI o'rniga oddiy rejim ishlaydi: raqam so'raydi. 0 — AI to'xtatilgan.", max_digits=8, verbose_name='kunlik budjet ($)')),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text="80 foiziga yetganda Telegram'ga ogohlantirish keladi.", max_digits=8, verbose_name='oylik budjet ($)')),
                ('max_user_messages', models.PositiveSmallIntegerField(default=30, help_text="Undan keyin AI javob bermaydi va raqam qoldirishni so'raydi.", verbose_name='bitta suhbatdagi xabarlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
            ],
            options={
                'verbose_name': 'AI sozlamalari',
                'verbose_name_plural': 'AI sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('channel', models.CharField(choices=[('WEB', 'Sayt'), ('TELEGRAM', 'Telegram')], db_index=True, default='WEB', max_length=10, verbose_name='kanal')),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('MANAGER', 'Menejer kerak'), ('CLOSED', 'Yopilgan')], db_index=True, default='OPEN', max_length=10, verbose_name='holat')),
                ('token_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram chat')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='ism')),
                ('locale', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='til')),
                ('source_page', models.CharField(blank=True, max_length=500, verbose_name='boshlangan sahifa')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='kontekst')),
                ('phones', models.JSONField(blank=True, default=dict, editable=False)),
                ('summary', models.TextField(blank=True, verbose_name='menejer uchun xulosa')),
                ('user_messages', models.PositiveSmallIntegerField(default=0, verbose_name='mijoz xabarlari')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='xarajat ($)')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='oxirgi xabar')),
                ('pending_since', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ip_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='anonimlashtirilgan')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='leads.lead', verbose_name='ariza')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'suhbat',
                'verbose_name_plural': 'suhbatlar',
                'ordering': ('-last_message_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Mijoz'), ('ASSISTANT', 'AI'), ('TOOL', 'Vosita natijasi')], max_length=10, verbose_name='kim')),
                ('text', models.TextField(blank=True, verbose_name='matn')),
                ('content', models.JSONField(default=list)),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='kurs kartochkalari')),
                ('model', models.CharField(blank=True, max_length=60, verbose_name='model')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='narx ($)')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='javob vaqti (ms)')),
                ('rating', models.SmallIntegerField(blank=True, choices=[(1, '👍'), (-1, '👎')], null=True, verbose_name='baho')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='vaqt')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation', verbose_name='suhbat')),
            ],
            options={
                'verbose_name': 'xabar',
                'verbose_name_plural': 'xabarlar',
                'ordering': ('id',),
            },
        ),
    ]
