# Generated by Django 5.2.17 on 2026-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='ism')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='username')),
                ('language', models.CharField(blank=True, choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], max_length=2, verbose_name='til')),
                ('news', models.BooleanField(default=True, help_text="O'chirilsa, admin xabarlari botda kelmaydi.", verbose_name='yangiliklar')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='botni bloklagan')),
                ('referral_code', models.CharField(blank=True, max_length=16, verbose_name='taklif kodi')),
                ('state', models.JSONField(blank=True, default=dict, editable=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='oxirgi faollik')),
            ],
            options={
                'verbose_name': 'bot foydalanuvchisi',
                'verbose_name_plural': 'bot foydalanuvchilari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='nomi')),
                ('chat', models.CharField(help_text="@kanal_nomi yoki yopiq kanal ID si (-100…). Bot kanalda administrator bo'lsin.", max_length=100, verbose_name='kanal')),
                ('url', models.URLField(help_text='https://t.me/kanal_nomi yoki taklif havolasi', verbose_name='havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'majburiy kanal',
                'verbose_name_plural': 'majburiy kanallar',
                'ordering': ('order', 'id'),
            },
        ),
    ]
