# Generated by Django 5.2.17 on 2026-09-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchat',
            name='verified_phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='tasdiqlangan telefon'),
        ),
    ]
