# Generated by Django 5.2.17 on 2026-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botchat_verified_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchat',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='manba'),
        ),
    ]
