# Generated by Django 5.2.17 on 2026-09-29 03:02

import apps.notifications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_lesson_materials'),
        ('learning', '0002_studygroup_enrollment_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(max_length=120, verbose_name='sarlavha')),
                ('body', models.TextField(max_length=2000, verbose_name='matn')),
                ('link', models.CharField(blank=True, help_text="Ixtiyoriy: https://meet.google.com/... yoki sayt ichidagi yo'l, masalan /dashboard/courses", max_length=500, validators=[apps.notifications.models.validate_link], verbose_name='havola')),
                ('kind', models.CharField(choices=[('INFO', "O'quv xabari"), ('PROMO', 'Aksiya va yangilik')], default='INFO', help_text='Aksiya Telegram va SMS orqali faqat rozilik berganlarga boradi, kechasi (22:00–09:00) esa ertalab 09:00 ga suriladi.', max_length=10, verbose_name='turi')),
                ('audience', models.CharField(choices=[('ALL', 'Hamma'), ('ADULT', 'Kattalar'), ('KIDS', 'SIFAT Kids')], default='ALL', max_length=10, verbose_name='kabinet')),
                ('without_course', models.BooleanField(default=False, help_text="Birorta kursga yozilmagan o'quvchilar (masalan, ro'yxatdan o'tib ketganlar).", verbose_name='faqat kurs tanlamaganlar')),
                ('joined_from', models.DateField(blank=True, null=True, verbose_name="ro'yxatdan o'tgan: dan")),
                ('joined_to', models.DateField(blank=True, null=True, verbose_name="ro'yxatdan o'tgan: gacha")),
                ('send_telegram', models.BooleanField(default=True, help_text="Telegram'ini ulagan o'quvchilarga.", verbose_name='Telegram')),
                ('send_sms', models.BooleanField(default=False, help_text="Telegram'i yo'qlarga SMS. Pullik; matn Eskiz'da tasdiqlangan shablonga mos bo'lishi kerak, aks holda Eskiz uni yubormaydi.", verbose_name='SMS')),
                ('sms_text', models.CharField(blank=True, max_length=300, verbose_name='SMS matni')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('SCHEDULED', 'Navbatda'), ('SENT', 'Yuborildi')], db_index=True, default='DRAFT', max_length=10, verbose_name='holat')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='yuborish vaqti')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='yuborilgan')),
                ('recipients', models.PositiveIntegerField(default=0, verbose_name='qabul qiluvchilar')),
                ('courses', models.ManyToManyField(blank=True, help_text="Tanlansa — faqat shu kurslarga yozilgan o'quvchilar.", related_name='+', to='catalog.course', verbose_name='kurslar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='muallif')),
                ('groups', models.ManyToManyField(blank=True, help_text="Tanlansa — faqat shu guruhlar o'quvchilari.", related_name='+', to='learning.studygroup', verbose_name='guruhlar')),
            ],
            options={
                'verbose_name': 'xabar',
                'verbose_name_plural': 'xabar yuborish',
                'ordering': ('-created_at',),
                'permissions': [('send_broadcast', 'Xabarni yuborish')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BROADCAST', 'Xabar'), ('PAYMENT', "To'lov"), ('COURSE_OPENED', 'Kurs ochildi'), ('ACCESS_EXPIRING', 'Muddat tugayapti'), ('ACCESS_EXPIRED', 'Muddat tugadi'), ('TEST', 'Sinov')], max_length=20, verbose_name='turi')),
                ('title', models.CharField(max_length=120, verbose_name='sarlavha')),
                ('body', models.TextField(blank=True, verbose_name='matn')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='havola')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='vaqt')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="o'qilgan")),
                ('telegram', models.CharField(blank=True, choices=[('QUEUED', 'Navbatda'), ('SENT', 'Yuborildi'), ('FAILED', 'Yetmadi')], max_length=10, verbose_name='Telegram')),
                ('sms', models.CharField(blank=True, choices=[('QUEUED', 'Navbatda'), ('SENT', 'Yuborildi'), ('FAILED', 'Yetmadi')], max_length=10, verbose_name='SMS')),
                ('sms_text', models.CharField(blank=True, max_length=300, verbose_name='SMS matni')),
                ('error', models.CharField(blank=True, max_length=300, verbose_name='yetkazish xatosi')),
                ('dedupe_key', models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True)),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.broadcast', verbose_name='xabar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'yuborilgan xabar',
                'verbose_name_plural': 'yuborilgan xabarlar',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
                'constraints': [models.UniqueConstraint(fields=('broadcast', 'user'), name='unique_broadcast_recipient')],
            },
        ),
    ]
