# Generated by Django 5.2.17 on 2026-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('BROADCAST', 'Xabar'), ('PAYMENT', "To'lov"), ('COURSE_OPENED', 'Kurs ochildi'), ('ACCESS_EXPIRING', 'Muddat tugayapti'), ('ACCESS_EXPIRED', 'Muddat tugadi'), ('HOMEWORK_SUBMITTED', 'Yangi uy vazifasi javobi'), ('HOMEWORK_REVIEWED', 'Uy vazifasi tekshirildi'), ('TEST', 'Sinov')], max_length=20, verbose_name='turi'),
        ),
    ]
