# Generated by Django 5.2.17 on 2026-09-30 06:45

import apps.core.storage
import apps.notifications.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_kind'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='bot_all',
            field=models.BooleanField(default=False, help_text="Botga /start bosgan hamma (ro'yxatdan o'tmaganlar ham) Telegram'da oladi. Faqat filtrsiz xabarda; kechasi (22:00–09:00) yozilgani ertalab 09:00 da ketadi.", verbose_name='botdagi hammaga ham'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='bot_failed',
            field=models.PositiveIntegerField(default=0, verbose_name='botda yetmadi'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='bot_recipients',
            field=models.PositiveIntegerField(default=0, verbose_name='bot orqali'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='bot_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='botda yetdi'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, help_text="Ixtiyoriy: Telegram'da xabar bilan birga ketadi (JPG yoki PNG).", storage=apps.core.storage.public_storage, upload_to=apps.notifications.models.broadcast_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='rasm'),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='rasm'),
        ),
        migrations.AddField(
            model_name='notification',
            name='quiz',
            field=models.ForeignKey(blank=True, help_text='Telegram\'da "Testni boshlash" tugmasi — test botda ochiladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quizzes.quiz', verbose_name='test'),
        ),
    ]
