# Generated by Django 5.2.17 on 2026-09-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('BROADCAST', 'Xabar'), ('PAYMENT', "To'lov"), ('COURSE_OPENED', 'Kurs ochildi'), ('ACCESS_EXPIRING', 'Muddat tugayapti'), ('ACCESS_EXPIRED', 'Muddat tugadi'), ('HOMEWORK_SUBMITTED', 'Yangi uy vazifasi javobi'), ('HOMEWORK_REVIEWED', 'Uy vazifasi tekshirildi'), ('INACTIVE', "O'qishga qaytish eslatmasi"), ('LIVE_REMINDER', 'Jonli dars eslatmasi'), ('LIVE_CANCELED', 'Dars bekor qilindi'), ('LIVE_ABSENT', "Darsda bo'lmadi"), ('LIVE_RECORDING', 'Dars yozuvi'), ('LESSON_OPENED', 'Yangi dars ochildi'), ('EXAM_DRAFT', 'Imtihonni tayyorlash'), ('EXAM_OPENED', 'Imtihon ochildi'), ('EXAM_RESULT', 'Imtihon natijasi'), ('CERTIFICATE', 'Sertifikat'), ('REWARD', 'Mukofot'), ('TEST', 'Sinov')], max_length=20, verbose_name='turi'),
        ),
    ]
