# Generated by Django 5.2.17 on 2026-09-26 07:40

import apps.users.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='telefon')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='ism')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='familiya')),
                ('locale', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='interfeys tili')),
                ('is_active', models.BooleanField(default=True, help_text='Foydalanuvchini bloklash uchun belgini olib tashlang.', verbose_name='faol')),
                ('is_staff', models.BooleanField(default=False, help_text='Admin panelga kira oladi.', verbose_name='xodim')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="ro'yxatdan o'tgan sana")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'foydalanuvchi',
                'verbose_name_plural': 'foydalanuvchilar',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
