# Generated by Django 5.2.17 on 2026-09-27 08:12

import apps.core.storage
import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, storage=apps.core.storage.public_storage, upload_to=apps.users.models.avatar_path, verbose_name='rasm'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='oferta va maxfiylik siyosati qabul qilingan'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Masalan: offer:1.0, privacy:1.0', max_length=80, verbose_name='qabul qilingan versiyalar'),
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=13, verbose_name='telefon')),
                ('purpose', models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('reset', 'Parolni tiklash')], max_length=10, verbose_name='maqsad')),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='urinishlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yuborilgan')),
                ('expires_at', models.DateTimeField(verbose_name='amal qiladi')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='yopilgan')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'SMS kod',
                'verbose_name_plural': 'SMS kodlar',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'purpose', '-created_at'], name='users_oneti_phone_990977_idx')],
            },
        ),
    ]
