# Generated by Django 5.2.17 on 2026-09-27 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='purpose',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('reset', 'Parolni tiklash'), ('link', "Google yoki Telegram'ni bog'lash")], max_length=10, verbose_name='maqsad'),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('telegram', 'Telegram')], max_length=20, verbose_name='provayder')),
                ('uid', models.CharField(max_length=64, verbose_name='provayderdagi id')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="bog'langan")),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='oxirgi kirish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'ijtimoiy akkaunt',
                'verbose_name_plural': 'ijtimoiy akkauntlar',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('provider', 'uid'), name='unique_social_identity'), models.UniqueConstraint(fields=('provider', 'user'), name='unique_provider_per_user')],
            },
        ),
    ]
