# Generated by Django 5.2.17 on 2026-09-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_onetimecode_purpose_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audience',
            field=models.CharField(choices=[('ADULT', '15 yoshdan katta'), ('KIDS', 'Bolalar (7–11 yosh)')], default='ADULT', max_length=10, verbose_name="kabinet ko'rinishi"),
        ),
    ]
