# Generated by Django 5.2.17 on 2026-09-29 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bot bloklangan'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='notify',
            field=models.BooleanField(default=True, verbose_name='xabarlar yuborilsin'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, help_text="Bo'sh bo'lsa, aksiyalar Telegram va SMS orqali yuborilmaydi (kabinetda ko'rinadi).", null=True, verbose_name='aksiya va yangiliklarga rozilik'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="ro'yxatdan o'tgan sana"),
        ),
    ]
