# Generated by Django 5.2.17 on 2026-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_source',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='manba'),
        ),
    ]
