# Generated by Django 5.2.17 on 2026-09-26 15:05

import apps.core.storage
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rinadi")),
                ('problem', models.CharField(max_length=120, verbose_name='xavotir')),
                ('problem_uz', models.CharField(max_length=120, null=True, verbose_name='xavotir')),
                ('problem_ru', models.CharField(max_length=120, null=True, verbose_name='xavotir')),
                ('problem_en', models.CharField(max_length=120, null=True, verbose_name='xavotir')),
                ('answer', models.CharField(max_length=240, verbose_name='javob')),
                ('answer_uz', models.CharField(max_length=240, null=True, verbose_name='javob')),
                ('answer_ru', models.CharField(max_length=240, null=True, verbose_name='javob')),
                ('answer_en', models.CharField(max_length=240, null=True, verbose_name='javob')),
            ],
            options={
                'verbose_name': 'xavotir',
                'verbose_name_plural': 'xavotirlar',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, help_text="«Biz kimmiz» bo'limidagi manifest: 2–4 gap.", verbose_name='biz haqimizda'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(blank=True, help_text="«Biz kimmiz» bo'limidagi manifest: 2–4 gap.", null=True, verbose_name='biz haqimizda'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ru',
            field=models.TextField(blank=True, help_text="«Biz kimmiz» bo'limidagi manifest: 2–4 gap.", null=True, verbose_name='biz haqimizda'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_uz',
            field=models.TextField(blank=True, help_text="«Biz kimmiz» bo'limidagi manifest: 2–4 gap.", null=True, verbose_name='biz haqimizda'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_poster',
            field=models.ImageField(blank=True, help_text="Video boshlanishidan oldin ko'rinadigan rasm (16:9).", storage=apps.core.storage.public_storage, upload_to='promo/', verbose_name='video muqovasi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video',
            field=models.FileField(blank=True, help_text="MP4 (H.264) yoki WebM, 200 MB gacha. Bo'lmasa, saytda animatsion rolik ko'rsatiladi.", storage=apps.core.storage.public_storage, upload_to='promo/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm']), apps.core.validators.MaxFileSizeValidator(200)], verbose_name='promo video'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(help_text="Ajratib ko'rsatiladigan so'zni yulduzchalar ichiga oling: *kod*", max_length=200, verbose_name='hero sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(help_text="Ajratib ko'rsatiladigan so'zni yulduzchalar ichiga oling: *kod*", max_length=200, null=True, verbose_name='hero sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_ru',
            field=models.CharField(help_text="Ajratib ko'rsatiladigan so'zni yulduzchalar ichiga oling: *kod*", max_length=200, null=True, verbose_name='hero sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_uz',
            field=models.CharField(help_text="Ajratib ko'rsatiladigan so'zni yulduzchalar ichiga oling: *kod*", max_length=200, null=True, verbose_name='hero sarlavhasi'),
        ),
    ]
