# Generated by Django 5.2.17 on 2026-10-03 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0004_studygroup_teacher_paced'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('day', models.DateField(db_index=True, verbose_name='kun')),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('CLOSED', 'Yopilgan'), ('SKIPPED', 'Savollar yetarli emas')], db_index=True, default='OPEN', max_length=10, verbose_name='holat')),
                ('questions_count', models.PositiveSmallIntegerField(default=20, verbose_name='savollar soni')),
                ('pool_size', models.PositiveIntegerField(default=0, help_text="O'tilgan darslar testlaridagi savollar.", verbose_name='savollar banki')),
                ('opens_at', models.DateTimeField(verbose_name='ochiladi')),
                ('closes_at', models.DateTimeField(verbose_name='yopiladi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tests', to='learning.studygroup', verbose_name='guruh')),
            ],
            options={
                'verbose_name': 'kunlik test',
                'verbose_name_plural': 'kunlik testlar',
                'ordering': ('-day', 'group_id'),
            },
        ),
        migrations.CreateModel(
            name='DailyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list, editable=False)),
                ('seed', models.PositiveIntegerField(default=0, editable=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='boshlangan')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='tugagan')),
                ('correct', models.PositiveSmallIntegerField(default=0, verbose_name="to'g'ri")),
                ('total', models.PositiveSmallIntegerField(default=0, verbose_name='savollar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attempts', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='dailytest.dailytest', verbose_name='test')),
            ],
            options={
                'verbose_name': 'kunlik test natijasi',
                'verbose_name_plural': 'kunlik test natijalari',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(default=dict, verbose_name='javob')),
                ('correct', models.BooleanField(default=False, verbose_name="to'g'ri")),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dailytest.dailyattempt')),
            ],
            options={
                'verbose_name': 'javob',
                'verbose_name_plural': 'javoblar',
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_daily_answer')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailytest',
            constraint=models.UniqueConstraint(fields=('group', 'day'), name='unique_daily_test_per_day'),
        ),
        migrations.AddConstraint(
            model_name='dailyattempt',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='unique_daily_attempt'),
        ),
    ]
