# Generated by Django 5.2.17 on 2026-09-27 12:11

import apps.core.storage
import apps.videos.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identifikator')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='nomi')),
                ('status', models.CharField(choices=[('UPLOADING', 'Yuklanmoqda'), ('PROCESSING', 'Qayta ishlanmoqda'), ('READY', 'Tayyor'), ('FAILED', 'Xato')], db_index=True, default='UPLOADING', max_length=20, verbose_name='holat')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='fayl nomi')),
                ('source_key', models.CharField(blank=True, max_length=255, verbose_name='xom fayl kaliti')),
                ('source_size', models.BigIntegerField(default=0, verbose_name='hajmi (bayt)')),
                ('upload_id', models.CharField(blank=True, max_length=255, verbose_name='multipart id')),
                ('duration_sec', models.PositiveIntegerField(default=0, verbose_name='davomiyligi (soniya)')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='kengligi')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='balandligi')),
                ('variants', models.JSONField(blank=True, default=list, verbose_name='sifatlar')),
                ('thumbnail', models.ImageField(blank=True, storage=apps.core.storage.public_storage, upload_to=apps.videos.models.thumbnail_path, verbose_name='suratcha')),
                ('sealed_key', models.TextField(blank=True, editable=False, verbose_name='shifrlash kaliti')),
                ('error', models.TextField(blank=True, verbose_name='xato')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='yuklagan')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videolar',
                'ordering': ('-created_at',),
            },
        ),
    ]
