# Generated by Django 5.2.17 on 2026-09-27 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_course_audience_format_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='ACTIVE', max_length=10, verbose_name='holat')),
                ('source', models.CharField(choices=[('PAYMENT', "To'lov"), ('MANUAL', "Qo'lda berilgan"), ('FREE', 'Bepul kurs')], default='MANUAL', max_length=10, verbose_name='manba')),
                ('study_format', models.CharField(choices=[('ONLINE', 'Onlayn'), ('OFFLINE', 'Offlayn')], default='ONLINE', max_length=10, verbose_name='shakl')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Offlayn (oylik) to'lov uchun. Bo'sh bo'lsa — cheklanmagan.", null=True, verbose_name='amal qilish muddati')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='catalog.course', verbose_name='kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'kursga yozilish',
                'verbose_name_plural': 'kursga yozilishlar',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('position_sec', models.PositiveIntegerField(default=0, verbose_name="to'xtagan joyi (soniya)")),
                ('watched_sec', models.PositiveIntegerField(default=0, verbose_name="ko'rilgan (soniya)")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tugatilgan')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='catalog.lesson', verbose_name='dars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'dars progressi',
                'verbose_name_plural': 'dars progressi',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='unique_lesson_progress')],
            },
        ),
    ]
