# Generated by Django 5.2.17 on 2026-09-28 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_lesson_materials'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(help_text='Masalan: FE-12 yoki Kids-3', max_length=60, verbose_name='nomi')),
                ('study_format', models.CharField(choices=[('ONLINE', 'Onlayn'), ('OFFLINE', 'Offlayn')], default='OFFLINE', max_length=10, verbose_name='shakl')),
                ('schedule', models.CharField(blank=True, help_text='Masalan: Du, Chor, Ju — 18:00', max_length=120, verbose_name='jadval')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='boshlanish sanasi')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="o'rinlar soni")),
                ('status', models.CharField(choices=[('FORMING', "Yig'ilmoqda"), ('ACTIVE', "O'qiyapti"), ('FINISHED', 'Tugagan')], db_index=True, default='FORMING', max_length=10, verbose_name='holat')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_groups', to='catalog.course', verbose_name='kurs')),
                ('teacher', models.ForeignKey(limit_choices_to={'groups__name': 'TEACHER'}, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name="o'qituvchi")),
            ],
            options={
                'verbose_name': 'guruh',
                'verbose_name_plural': 'guruhlar',
                'ordering': ('-starts_on', 'name'),
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='learning.studygroup', verbose_name='guruh'),
        ),
        migrations.AddConstraint(
            model_name='studygroup',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_group_name_per_course'),
        ),
    ]
