# Generated by Django 5.2.17 on 2026-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_studygroup_enrollment_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='meet_url',
            field=models.URLField(blank=True, help_text='Onlayn guruh uchun.', verbose_name='doimiy Meet yoki Zoom havolasi'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='room',
            field=models.CharField(blank=True, help_text='Offlayn guruh uchun.', max_length=60, verbose_name='xona'),
        ),
    ]
