# Generated by Django 5.2.17 on 2026-10-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_studygroup_meet_url_studygroup_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='teacher_paced',
            field=models.BooleanField(default=False, help_text="Onlayn (Zoom, videosiz) guruh uchun: test va uy vazifalari o'qituvchi «Dars o'tildi» deb belgilagan darsgacha ochiladi, testdan o'tish sharti yo'q. Offlayn guruhda doim shunday.", verbose_name="darslarni o'qituvchi ochadi"),
        ),
    ]
