# Generated by Django 5.2.17 on 2026-09-30 21:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_course_certificate_course_monthly_exam'),
        ('homework', '0001_initial'),
        ('live', '0002_grouplesson'),
        ('payments', '0002_order_discount_percent_order_discount_reason_and_more'),
        ('quizzes', '0001_initial'),
        ('users', '0007_user_referral_code_user_referred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_xp', models.PositiveSmallIntegerField(default=10, verbose_name='dars tugatildi (XP)')),
                ('quiz_xp', models.PositiveSmallIntegerField(default=15, verbose_name="dars testidan birinchi marta o'tildi (XP)")),
                ('homework_xp', models.PositiveSmallIntegerField(default=20, verbose_name='uy vazifasi topshirildi (XP)')),
                ('attendance_xp', models.PositiveSmallIntegerField(default=10, verbose_name='darsga vaqtida kelindi (XP)')),
                ('exam_xp', models.PositiveSmallIntegerField(default=50, verbose_name="oylik imtihondan o'tildi (XP)")),
                ('daily_bonus_xp', models.PositiveSmallIntegerField(default=10, verbose_name='kunlik topshiriqlar bajarildi — bonus (XP)')),
                ('daily_missed_penalty', models.PositiveSmallIntegerField(default=5, verbose_name='kunlik topshiriqlar bajarilmadi (−XP)')),
                ('absent_penalty', models.PositiveSmallIntegerField(default=15, verbose_name='darsga sababsiz kelmadi (−XP)')),
                ('late_penalty', models.PositiveSmallIntegerField(default=5, verbose_name='darsga kechikdi (−XP)')),
                ('homework_late_penalty', models.PositiveSmallIntegerField(default=10, verbose_name='uy vazifasi muddatidan kechikdi (−XP)')),
                ('referral_lesson_coins', models.PositiveSmallIntegerField(default=50, verbose_name="do'st birinchi darsni tugatdi (coin)")),
                ('referral_paid_coins', models.PositiveSmallIntegerField(default=100, verbose_name="do'st to'lov qildi (coin)")),
                ('referral_discount', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(90)], verbose_name="do'stning birinchi to'loviga chegirma (%)")),
                ('coupon_percent', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='taklif qilganga kupon (%)')),
                ('daily_tasks', models.BooleanField(default=True, help_text="Har kuni 09:00 da har bir faol o'quvchiga 3 ta topshiriq.", verbose_name='kunlik topshiriqlar')),
                ('announce_winners', models.BooleanField(default=False, help_text="Dushanba 10:00 da o'tgan haftaning eng yaxshi 3 o'quvchisi majburiy kanalga.", verbose_name="haftalik g'oliblarni kanalga e'lon qilish")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'XP va coin sozlamalari',
                'verbose_name_plural': 'XP va coin sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='XP')),
                ('coins', models.PositiveIntegerField(default=0, verbose_name='coin')),
                ('streak', models.PositiveSmallIntegerField(default=0, verbose_name='seriya (kun)')),
                ('best_streak', models.PositiveSmallIntegerField(default=0, verbose_name='eng uzun seriya')),
                ('streak_day', models.DateField(blank=True, null=True, verbose_name="oxirgi to'liq kun")),
                ('hidden', models.BooleanField(default=False, help_text="O'quvchi sozlamalarda o'zi yoqadi.", verbose_name="reytingda ko'rsatilmasin")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hamyon',
                'verbose_name_plural': 'hamyonlar',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(verbose_name='chegirma (%)')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='berilgan')),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim sababli')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='payments.order', verbose_name='buyurtma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='egasi')),
            ],
            options={
                'verbose_name': 'kupon',
                'verbose_name_plural': 'kuponlar',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ReviewAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list)),
                ('seed', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'takrorlash',
                'verbose_name_plural': 'takrorlashlar',
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='kun')),
                ('kind', models.CharField(choices=[('LESSON', "Keyingi darsni ko'rish"), ('QUIZ', "Dars testidan o'tish"), ('REVIEW', 'Botda takrorlash (5 savol)'), ('HOMEWORK', 'Uy vazifasini topshirish'), ('LIVE', 'Bugungi darsga vaqtida kelish')], max_length=10, verbose_name='topshiriq')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='nima')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='bajarildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='homework.assignment')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.lesson')),
                ('live_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='live.livelesson')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'kunlik topshiriq',
                'verbose_name_plural': 'kunlik topshiriqlar',
                'ordering': ('-day', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('user', 'day', 'kind'), name='unique_daily_task')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('LESSON', 'Dars tugatildi'), ('QUIZ', "Dars testidan o'tildi"), ('HOMEWORK', 'Uy vazifasi topshirildi'), ('ATTENDANCE', 'Darsga vaqtida kelindi'), ('EXAM', "Oylik imtihondan o'tildi"), ('DAILY', 'Kunlik topshiriqlar bajarildi'), ('DAILY_MISSED', 'Kunlik topshiriqlar bajarilmadi'), ('ABSENT', 'Darsga sababsiz kelmadi'), ('LATE', 'Darsga kechikdi'), ('HOMEWORK_LATE', 'Uy vazifasi muddatidan kechikdi'), ('REFERRAL', "Do'st birinchi darsni tugatdi"), ('REFERRAL_PAID', "Do'st to'lov qildi"), ('PURCHASE', "Do'kondan sovg'a"), ('REFUND', "Sovg'a bekor qilindi"), ('MANUAL', "Qo'lda")], db_index=True, max_length=20, verbose_name='sabab')),
                ('xp', models.IntegerField(default=0, verbose_name='XP')),
                ('applied_xp', models.IntegerField(default=0, editable=False, verbose_name='hisoblangan XP')),
                ('coins', models.IntegerField(default=0, verbose_name='coin')),
                ('key', models.CharField(editable=False, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='vaqt')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='bekor qilingan')),
                ('cancel_reason', models.CharField(blank=True, max_length=300, verbose_name='bekor qilish sababi')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim bekor qildi')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.course', verbose_name='kurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="kim qo'shdi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_entries', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'XP va coin tarixi',
                'verbose_name_plural': 'XP va coin tarixi',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['user', 'created_at'], name='rewards_ent_user_id_8b6a1e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('canceled_at__isnull', True)), fields=('key',), name='unique_active_reward_key')],
            },
        ),
    ]
