# Generated by Django 5.2.17 on 2026-10-03 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Bo'sh — muddatsiz.", null=True, verbose_name='amal qiladi (gacha)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='kind',
            field=models.CharField(choices=[('REFERRAL', "Do'st taklifi"), ('PLACEMENT', 'Daraja testi'), ('MANUAL', "Qo'lda")], db_index=True, default='REFERRAL', max_length=10, verbose_name='turi'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='placement_coupon_hours',
            field=models.PositiveSmallIntegerField(default=72, verbose_name='daraja testi kuponi muddati (soat)'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='placement_good_percent',
            field=models.PositiveSmallIntegerField(default=70, help_text='Shundan yuqori natija — katta chegirma.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='daraja testi: yaxshi natija (%)'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='placement_high_coupon',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='daraja testi: yaxshi natijaga kupon (%)'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='placement_low_coupon',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='daraja testi: boshqa natijaga kupon (%)'),
        ),
    ]
