# Generated by Django 5.2.17 on 2026-10-03 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_coupon_expires_at_coupon_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='daily_test',
            field=models.BooleanField(default=True, help_text="Har kuni 07:00 da guruhdagi har o'quvchiga botda test (guruhda o'tilgan darslar testlaridan), 23:00 da yopiladi. Jarima yo'q.", verbose_name='guruhlarga kunlik test'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='daily_test_coins',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="kunlik test: har to'g'ri javobga coin"),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='daily_test_questions',
            field=models.PositiveSmallIntegerField(default=20, help_text="Kamida 20. O'tilgan darslarda shuncha savol bo'lmasa — test berilmaydi.", validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)], verbose_name='kunlik test: savollar soni'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='daily_test_xp',
            field=models.PositiveSmallIntegerField(default=2, verbose_name="kunlik test: har to'g'ri javobga XP"),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reason',
            field=models.CharField(choices=[('LESSON', 'Dars tugatildi'), ('QUIZ', "Dars testidan o'tildi"), ('HOMEWORK', 'Uy vazifasi topshirildi'), ('ATTENDANCE', 'Darsga vaqtida kelindi'), ('EXAM', "Oylik imtihondan o'tildi"), ('DAILY', 'Kunlik topshiriqlar bajarildi'), ('DAILY_MISSED', 'Kunlik topshiriqlar bajarilmadi'), ('DAILY_TEST', 'Kunlik test'), ('ABSENT', 'Darsga sababsiz kelmadi'), ('LATE', 'Darsga kechikdi'), ('HOMEWORK_LATE', 'Uy vazifasi muddatidan kechikdi'), ('REFERRAL', "Do'st birinchi darsni tugatdi"), ('REFERRAL_PAID', "Do'st to'lov qildi"), ('PURCHASE', "Do'kondan sovg'a"), ('REFUND', "Sovg'a bekor qilindi"), ('MANUAL', "Qo'lda")], db_index=True, max_length=20, verbose_name='sabab'),
        ),
    ]
