# Generated by Django 5.2.17 on 2026-09-30 21:39

import apps.core.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=120, verbose_name='nomi')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='nomi')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='nomi')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='tavsif')),
                ('image', models.ImageField(blank=True, storage=apps.core.storage.public_storage, upload_to='shop/', verbose_name='rasm')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='narx (coin)')),
                ('kind', models.CharField(choices=[('DIGITAL', 'Raqamli'), ('PHYSICAL', 'Jismoniy')], default='PHYSICAL', max_length=10, verbose_name='turi')),
                ('stock', models.PositiveIntegerField(blank=True, help_text="Bo'sh — cheksiz.", null=True, verbose_name='zaxira')),
                ('audience', models.CharField(choices=[('ALL', 'Hammaga'), ('ADULT', 'Kattalarga'), ('KIDS', 'SIFAT Kids')], default='ALL', max_length=10, verbose_name='kimga')),
                ('is_active', models.BooleanField(default=True, verbose_name='sotuvda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': "sovg'a",
                'verbose_name_plural': "sovg'alar",
                'ordering': ('order', 'price', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=120, verbose_name='nomi')),
                ('price', models.PositiveIntegerField(verbose_name='narx (coin)')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('READY', 'Tayyor'), ('DELIVERED', 'Topshirildi'), ('CANCELED', 'Bekor qilindi')], db_index=True, default='NEW', max_length=10, verbose_name='holat')),
                ('note', models.CharField(blank=True, help_text='Masalan: qayerdan va qachon olish mumkin.', max_length=300, verbose_name="izoh o'quvchiga")),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name="tayyor bo'ldi")),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='topshirildi')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='bekor qilindi')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='shop.product', verbose_name="sovg'a")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'buyurtma',
                'verbose_name_plural': "do'kon buyurtmalari",
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
