# Generated by Django 5.2.17 on 2026-10-03 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_course_certificate_course_monthly_exam'),
        ('quizzes', '0001_initial'),
        ('rewards', '0002_coupon_expires_at_coupon_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(help_text='Botdagi tugma, masalan: Python yoki Frontend.', max_length=60, verbose_name='nomi')),
                ('questions_count', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(50)], verbose_name='savollar soni')),
                ('duration_min', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(60)], verbose_name='vaqt (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('course', models.ForeignKey(help_text="Natija va ariza shu kurs bo'yicha.", on_delete=django.db.models.deletion.CASCADE, related_name='placement_tests', to='catalog.course', verbose_name="yo'nalish (kurs)")),
                ('quiz', models.ForeignKey(help_text="Dars testi (savollar banki). O'quvchilarga ko'rinmasligi uchun xizmat kursida (masalan, «Daraja testlari») saqlang.", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quizzes.quiz', verbose_name='savollar')),
            ],
            options={
                'verbose_name': 'daraja testi',
                'verbose_name_plural': 'daraja testlari',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list, editable=False)),
                ('seed', models.PositiveIntegerField(default=0, editable=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='boshlangan')),
                ('deadline', models.DateTimeField(verbose_name='vaqt tugaydi')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='tugagan')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='natija (%)')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rewards.coupon', verbose_name='kupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='placement.placementtest', verbose_name='test')),
            ],
            options={
                'verbose_name': 'daraja testi natijasi',
                'verbose_name_plural': 'daraja testi natijalari',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='PlacementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(default=dict, verbose_name='javob')),
                ('correct', models.BooleanField(default=False, verbose_name="to'g'ri")),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='placement.placementattempt')),
            ],
            options={
                'verbose_name': 'javob',
                'verbose_name_plural': 'javoblar',
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_placement_answer')],
            },
        ),
        migrations.AddIndex(
            model_name='placementattempt',
            index=models.Index(fields=['user', 'test'], name='placement_p_user_id_ea4e51_idx'),
        ),
    ]
