# Generated by Django 5.2.17 on 2026-09-26 13:06

import apps.core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'kategoriyalar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('full_name', models.CharField(max_length=150, verbose_name='ism-familiya')),
                ('position', models.CharField(blank=True, help_text='Masalan: Senior Frontend Developer', max_length=150, verbose_name='lavozim')),
                ('position_uz', models.CharField(blank=True, help_text='Masalan: Senior Frontend Developer', max_length=150, null=True, verbose_name='lavozim')),
                ('position_ru', models.CharField(blank=True, help_text='Masalan: Senior Frontend Developer', max_length=150, null=True, verbose_name='lavozim')),
                ('position_en', models.CharField(blank=True, help_text='Masalan: Senior Frontend Developer', max_length=150, null=True, verbose_name='lavozim')),
                ('bio', models.TextField(blank=True, verbose_name="qisqacha ma'lumot")),
                ('bio_uz', models.TextField(blank=True, null=True, verbose_name="qisqacha ma'lumot")),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name="qisqacha ma'lumot")),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name="qisqacha ma'lumot")),
                ('photo', models.ImageField(blank=True, storage=apps.core.storage.public_storage, upload_to='instructors/', verbose_name='rasm')),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tajriba (yil)')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rinadi")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='akkaunt')),
            ],
            options={
                'verbose_name': 'ustoz',
                'verbose_name_plural': 'ustozlar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='qisqa tavsif')),
                ('short_description_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqa tavsif')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqa tavsif')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqa tavsif')),
                ('description', models.TextField(blank=True, verbose_name="to'liq tavsif")),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name="to'liq tavsif")),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name="to'liq tavsif")),
                ('description_en', models.TextField(blank=True, null=True, verbose_name="to'liq tavsif")),
                ('level', models.CharField(choices=[('BEGINNER', "Boshlang'ich"), ('INTERMEDIATE', "O'rta"), ('ADVANCED', 'Yuqori')], default='BEGINNER', max_length=20, verbose_name='daraja')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('PUBLISHED', 'Nashr qilingan'), ('ARCHIVED', 'Arxivda')], db_index=True, default='DRAFT', max_length=20, verbose_name='holat')),
                ('price', models.PositiveIntegerField(default=0, verbose_name="narx (so'm)")),
                ('video_language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='video tili')),
                ('duration_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='davomiyligi (soat)')),
                ('icon', models.CharField(choices=[('code', 'Code'), ('server', 'Server'), ('database', 'Database'), ('palette', 'Palette'), ('smartphone', 'Smartphone'), ('brain', 'Brain'), ('terminal', 'Terminal'), ('shield', 'Shield')], default='code', help_text="Muqova rasmi bo'lmasa, kartochkada ko'rsatiladi.", max_length=20, verbose_name='belgi')),
                ('cover', models.ImageField(blank=True, storage=apps.core.storage.public_storage, upload_to='courses/', verbose_name='muqova')),
                ('is_featured', models.BooleanField(default=False, help_text="Landing'dagi kurslar bo'limida ko'rsatiladi.", verbose_name='bosh sahifada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='catalog.category', verbose_name='kategoriya')),
                ('instructors', models.ManyToManyField(blank=True, related_name='courses', to='catalog.instructor', verbose_name='ustozlar')),
            ],
            options={
                'verbose_name': 'kurs',
                'verbose_name_plural': 'kurslar',
                'ordering': ('order', 'id'),
            },
        ),
    ]
