# Generated by Django 5.2.17 on 2026-09-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='darslar soni'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_duration_min',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='dastur davomiyligi (daqiqa)'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='qisqacha')),
                ('summary_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqacha')),
                ('summary_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqacha')),
                ('summary_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqacha')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'modul',
                'verbose_name_plural': 'modullar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='qisqacha')),
                ('summary_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqacha')),
                ('summary_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqacha')),
                ('summary_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='qisqacha')),
                ('duration_min', models.PositiveSmallIntegerField(default=0, help_text="Dastur va kurs hajmini ko'rsatish uchun.", verbose_name='davomiyligi (daqiqa)')),
                ('is_preview', models.BooleanField(default=False, help_text="Sotib olmagan foydalanuvchi ham ko'ra oladi.", verbose_name='bepul dars')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalog.module', verbose_name='modul')),
            ],
            options={
                'verbose_name': 'dars',
                'verbose_name_plural': 'darslar',
                'ordering': ('order', 'id'),
            },
        ),
    ]
