# Generated by Django 5.2.17 on 2026-09-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_course_search_indexes'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='price_online',
        ),
        migrations.AddField(
            model_name='course',
            name='age_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='eng katta yosh'),
        ),
        migrations.AddField(
            model_name='course',
            name='age_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='eng kichik yosh'),
        ),
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.CharField(choices=[('ADULT', '15 yoshdan kattalar'), ('KIDS', 'Bolalar (7–11 yosh)')], db_index=True, default='ADULT', help_text="Kabinet ko'rinishi va katalog filtri shu qiymatga bog'liq.", max_length=10, verbose_name='kimga'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text="Bepul kursni ro'yxatdan o'tgan har kim o'qiy oladi.", verbose_name='bepul'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_offline_monthly',
            field=models.PositiveIntegerField(default=0, verbose_name="offlayn narx (oyiga, so'm)"),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_online',
            field=models.PositiveIntegerField(default=0, verbose_name="onlayn narx (bir marta, so'm)"),
        ),
        migrations.AddField(
            model_name='course',
            name='study_format',
            field=models.CharField(choices=[('ONLINE', 'Onlayn'), ('OFFLINE', 'Offlayn'), ('BOTH', 'Onlayn va offlayn')], default='ONLINE', max_length=10, verbose_name="o'qish shakli"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='videos.videoasset', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(choices=[('code', 'Code'), ('server', 'Server'), ('database', 'Database'), ('palette', 'Palette'), ('smartphone', 'Smartphone'), ('brain', 'Brain'), ('terminal', 'Terminal'), ('shield', 'Shield'), ('blocks', 'Blocks'), ('monitor', 'Monitor'), ('languages', 'Languages')], default='code', help_text="Muqova rasmi bo'lmasa, kartochkada ko'rsatiladi.", max_length=20, verbose_name='belgi'),
        ),
    ]
