# Generated by Django 5.2.17 on 2026-09-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_course_audience_format_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mxik_code',
            field=models.CharField(blank=True, help_text="Fiskal chek uchun. Soliq qo'mitasi ro'yxatidan olinadi.", max_length=20, verbose_name='MXIK (IKPU) kodi'),
        ),
    ]
