# Generated by Django 5.2.17 on 2026-09-27 17:35

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_course_mxik_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('kind', models.CharField(choices=[('FILE', 'Fayl'), ('LINK', 'Havola'), ('CODE', 'Kod')], default='FILE', max_length=10, verbose_name='turi')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('file', models.FileField(blank=True, upload_to=apps.catalog.models.material_path, verbose_name='fayl')),
                ('url', models.URLField(blank=True, verbose_name='havola')),
                ('code', models.TextField(blank=True, verbose_name='kod')),
                ('language', models.CharField(blank=True, help_text='Masalan: html, css, javascript, python.', max_length=30, verbose_name='dasturlash tili')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.lesson', verbose_name='dars')),
            ],
            options={
                'verbose_name': 'dars materiali',
                'verbose_name_plural': 'dars materiallari',
                'ordering': ('order', 'id'),
            },
        ),
    ]
