# Generated by Django 5.2.17 on 2026-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_lesson_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=True, help_text="Darslar, testlar, uy vazifalari va imtihonlar shartlari bajarilganda o'zi beriladi.", verbose_name='sertifikat beriladi'),
        ),
        migrations.AddField(
            model_name='course',
            name='monthly_exam',
            field=models.BooleanField(default=False, help_text="Har oyning 20-kuni imtihon qoralamasi o'zi yaratiladi; 25-kundan oy oxirigacha ochiq.", verbose_name='oylik imtihon'),
        ),
    ]
