# Generated by Django 5.2.17 on 2026-09-30 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_course_certificate_course_monthly_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='raqam')),
                ('full_name', models.CharField(help_text="Berilgan paytdagi ism (keyin o'zgarmaydi).", max_length=300, verbose_name='ism-familiya')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='ball')),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='berilgan')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='bekor qilingan')),
                ('revoke_reason', models.CharField(blank=True, max_length=300, verbose_name='bekor qilish sababi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='catalog.course', verbose_name='kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'sertifikat',
                'verbose_name_plural': 'sertifikatlar',
                'ordering': ('-issued_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_certificate_per_course')],
            },
        ),
    ]
