# Generated by Django 5.2.17 on 2026-09-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'statistika',
                'verbose_name_plural': 'statistika',
                'permissions': [('view_statistics', "Statistikani ko'rish")],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
