# Generated by Django 5.2.17 on 2026-09-30 19:31

import apps.exams.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_course_certificate_course_monthly_exam'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('month', models.DateField(help_text='Oyning birinchi kuni.', verbose_name='oy')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('READY', 'Tayyor')], db_index=True, default='DRAFT', help_text="Tayyor bo'lmagan imtihon ochilmaydi.", max_length=10, verbose_name='holat')),
                ('questions_count', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='test savollari')),
                ('duration_min', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)], verbose_name='test vaqti (daqiqa)')),
                ('pass_percent', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="o'tish bali (%)")),
                ('test_weight', models.PositiveSmallIntegerField(default=50, help_text='Natijadagi test qismining ulushi; qolgani — amaliy topshiriqlar.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='test ulushi (%)')),
                ('opens_at', models.DateTimeField(verbose_name='ochiladi')),
                ('closes_at', models.DateTimeField(verbose_name='yopiladi')),
                ('opened_notified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='catalog.course', verbose_name='kurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='muallif')),
                ('modules', models.ManyToManyField(blank=True, help_text="Test savollari shu modullar darslarining testlaridan. Bo'sh — hammasidan.", related_name='+', to='catalog.module', verbose_name='modullar')),
            ],
            options={
                'verbose_name': 'oylik imtihon',
                'verbose_name_plural': 'oylik imtihonlar',
                'ordering': ('-month', 'course__order', 'course_id'),
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list, editable=False)),
                ('seed', models.PositiveIntegerField(default=0, editable=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='boshlangan')),
                ('deadline', models.DateTimeField(verbose_name='vaqt tugaydi')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='tugagan')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='test natijasi (%)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='imtihon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'imtihon testi',
                'verbose_name_plural': 'imtihon testlari',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(default=dict, verbose_name='javob')),
                ('correct', models.BooleanField(default=False, verbose_name="to'g'ri")),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.question', verbose_name='savol')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt', verbose_name='urinish')),
            ],
            options={
                'verbose_name': 'imtihon javobi',
                'verbose_name_plural': 'imtihon javoblari',
                'ordering': ('answered_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExamExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField(verbose_name='muddat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='berilgan')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='exams.exam', verbose_name='imtihon')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='bergan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'alohida muddat',
                'verbose_name_plural': 'alohida muddatlar',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.PositiveSmallIntegerField(default=0, verbose_name='test (%)')),
                ('practical_score', models.PositiveSmallIntegerField(default=0, verbose_name='amaliy (%)')),
                ('total', models.PositiveSmallIntegerField(default=0, verbose_name='natija (%)')),
                ('passed', models.BooleanField(default=False, verbose_name="o'tdi")),
                ('final_at', models.DateTimeField(blank=True, null=True, verbose_name='yakunlangan')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam', verbose_name='imtihon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'imtihon natijasi',
                'verbose_name_plural': 'imtihon natijalari',
                'ordering': ('-exam__month', 'student_id'),
            },
        ),
        migrations.CreateModel(
            name='ExamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('instructions', models.TextField(verbose_name='topshiriq')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='exams.exam', verbose_name='imtihon')),
            ],
            options={
                'verbose_name': 'amaliy topshiriq',
                'verbose_name_plural': 'amaliy topshiriqlar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('text', models.TextField(blank=True, verbose_name='izoh')),
                ('code', models.TextField(blank=True, verbose_name='kod')),
                ('language', models.CharField(blank=True, max_length=20, verbose_name='kod tili')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='havola')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='baho')),
                ('feedback', models.TextField(blank=True, verbose_name="o'qituvchi izohi")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='baholangan')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='baholagan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_task_answers', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examtask', verbose_name='topshiriq')),
            ],
            options={
                'verbose_name': 'amaliy topshiriq javobi',
                'verbose_name_plural': 'amaliy topshiriq javoblari',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=apps.exams.models.task_file_path, verbose_name='fayl')),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('size', models.PositiveIntegerField(verbose_name='hajmi (bayt)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='turi')),
                ('is_image', models.BooleanField(default=False, verbose_name='rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yuklangan')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.taskanswer', verbose_name='javob')),
            ],
            options={
                'verbose_name': 'javob fayli',
                'verbose_name_plural': 'javob fayllari',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('course', 'month'), name='unique_exam_per_month'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_attempt'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_exam_answer'),
        ),
        migrations.AddConstraint(
            model_name='examextension',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_extension'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_result'),
        ),
        migrations.AddConstraint(
            model_name='taskanswer',
            constraint=models.UniqueConstraint(fields=('task', 'student'), name='unique_task_answer'),
        ),
    ]
