# Generated by Django 5.2.17 on 2026-09-29 11:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_lesson_materials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SINGLE', "Bitta to'g'ri javob"), ('MULTIPLE', "Bir nechta to'g'ri javob"), ('TEXT', 'Matn bilan javob'), ('ORDER', 'Tartiblash'), ('MATCH', 'Moslashtirish')], default='SINGLE', max_length=10, verbose_name='turi')),
                ('text', models.TextField(verbose_name='savol')),
                ('code', models.TextField(blank=True, help_text="Ixtiyoriy: savol ostida ko'rsatiladigan kod parchasi.", verbose_name='kod')),
                ('language', models.CharField(blank=True, max_length=20, verbose_name='kod tili')),
                ('explanation', models.TextField(blank=True, help_text="Javobdan keyin ko'rsatiladi: nega aynan shu javob.", verbose_name='izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'savol',
                'verbose_name_plural': 'savollar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='matn')),
                ('is_correct', models.BooleanField(default=False, verbose_name="to'g'ri")),
                ('match', models.CharField(blank=True, help_text='Faqat moslashtirish uchun.', max_length=500, verbose_name="juft (o'ng tomon)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question', verbose_name='savol')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variantlar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(default='Darsni tekshiring', max_length=200, verbose_name='sarlavha')),
                ('pass_percent', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="o'tish bali (%)")),
                ('questions_per_attempt', models.PositiveSmallIntegerField(default=0, help_text='0 — hammasi. Aks holda savollar bankidan tasodifiy shuncha savol.', verbose_name='har urinishda savollar')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='savollar tartibini aralashtirish')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='catalog.lesson', verbose_name='dars')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'testlar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='test'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list, editable=False)),
                ('seed', models.PositiveIntegerField(default=0, editable=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='boshlangan')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='tugagan')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='natija (%)')),
                ('stars', models.PositiveSmallIntegerField(default=0, verbose_name='yulduzlar')),
                ('passed', models.BooleanField(default=False, verbose_name="o'tdi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='test')),
            ],
            options={
                'verbose_name': 'test urinishi',
                'verbose_name_plural': 'test natijalari',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(default=dict, verbose_name='javob')),
                ('correct', models.BooleanField(default=False, verbose_name="to'g'ri")),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='vaqt')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.attempt', verbose_name='urinish')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question', verbose_name='savol')),
            ],
            options={
                'verbose_name': 'javob',
                'verbose_name_plural': 'javoblar',
                'ordering': ('answered_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_quiz_answer')],
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'quiz'], name='quizzes_att_student_eb00a8_idx'),
        ),
    ]
