# Generated by Django 5.2.17 on 2026-09-26 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=100, verbose_name='ism')),
                ('phone', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='telefon')),
                ('comment', models.TextField(blank=True, verbose_name='izoh')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('CONTACTED', "Bog'lanildi"), ('CONVERTED', 'Mijozga aylandi'), ('REJECTED', 'Rad etildi')], db_index=True, default='NEW', max_length=20, verbose_name='holat')),
                ('manager_note', models.TextField(blank=True, verbose_name='menejer izohi')),
                ('submissions', models.PositiveSmallIntegerField(default=1, help_text="Bitta raqamdan 24 soat ichida kelgan takroriy arizalar shu yerga qo'shiladi.", verbose_name='murojaatlar soni')),
                ('locale', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='til')),
                ('source_page', models.CharField(blank=True, max_length=500, verbose_name='manba sahifa')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='utm_campaign')),
                ('utm_term', models.CharField(blank=True, max_length=200, verbose_name='utm_term')),
                ('utm_content', models.CharField(blank=True, max_length=200, verbose_name='utm_content')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='brauzer')),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Telegram'ga yuborilgan")),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.course', verbose_name='qiziqqan kurs')),
            ],
            options={
                'verbose_name': 'ariza',
                'verbose_name_plural': 'arizalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
