# Generated by Django 5.2.17 on 2026-09-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('FORM', 'Sayt formasi'), ('AI_WEB', 'AI chat (sayt)'), ('AI_TELEGRAM', 'AI chat (Telegram)')], db_index=True, default='FORM', max_length=12, verbose_name='manba'),
        ),
    ]
