# Generated by Django 5.2.17 on 2026-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('FORM', 'Sayt formasi'), ('AI_WEB', 'AI chat (sayt)'), ('AI_TELEGRAM', 'AI chat (Telegram)'), ('BOT_TEST', 'Botdagi daraja testi')], db_index=True, default='FORM', max_length=12, verbose_name='manba'),
        ),
    ]
