# Generated by Django 5.2.17 on 2026-09-27 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_course_mxik_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('study_format', models.CharField(choices=[('ONLINE', 'Onlayn'), ('OFFLINE', 'Offlayn')], default='ONLINE', max_length=10, verbose_name='shakl')),
                ('months', models.PositiveSmallIntegerField(default=1, help_text="Offlayn to'lov uchun: nechta oyga to'langan.", verbose_name='oylar')),
                ('amount', models.PositiveIntegerField(verbose_name="summa (so'm)")),
                ('status', models.CharField(choices=[('NEW', "To'lov kutilmoqda"), ('PAID', "To'langan"), ('EXPIRED', "Muddati o'tgan"), ('CANCELLED', 'Bekor qilingan'), ('REFUNDED', 'Qaytarilgan')], db_index=True, default='NEW', max_length=10, verbose_name='holat')),
                ('provider', models.CharField(choices=[('CLICK', 'Click')], default='CLICK', max_length=10, verbose_name="to'lov tizimi")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="to'langan vaqt")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.course', verbose_name='kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='xaridor')),
            ],
            options={
                'verbose_name': 'buyurtma',
                'verbose_name_plural': 'buyurtmalar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('provider', models.CharField(choices=[('CLICK', 'Click')], default='CLICK', max_length=10, verbose_name="to'lov tizimi")),
                ('action', models.CharField(max_length=40, verbose_name='amal')),
                ('request', models.JSONField(blank=True, default=dict, verbose_name="so'rov")),
                ('response', models.JSONField(blank=True, default=dict, verbose_name='javob')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='payments.order', verbose_name='buyurtma')),
            ],
            options={
                'verbose_name': "to'lov logi",
                'verbose_name_plural': "to'lov loglari",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('provider', models.CharField(choices=[('CLICK', 'Click')], default='CLICK', max_length=10, verbose_name="to'lov tizimi")),
                ('provider_trans_id', models.CharField(max_length=64, verbose_name='tranzaksiya raqami')),
                ('paydoc_id', models.CharField(blank=True, max_length=64, verbose_name="to'lov hujjati")),
                ('amount', models.PositiveIntegerField(verbose_name="summa (so'm)")),
                ('status', models.CharField(choices=[('PREPARED', 'Tayyorlangan'), ('CONFIRMED', 'Tasdiqlangan'), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='PREPARED', max_length=10, verbose_name='holat')),
                ('fiscal_receipt_url', models.URLField(blank=True, verbose_name='fiskal chek')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqt')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='bekor qilingan vaqt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.order', verbose_name='buyurtma')),
            ],
            options={
                'verbose_name': "to'lov tranzaksiyasi",
                'verbose_name_plural': "to'lov tranzaksiyalari",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('amount', models.PositiveIntegerField(verbose_name="summa (so'm)")),
                ('reason', models.TextField(blank=True, verbose_name='sabab')),
                ('status', models.CharField(choices=[('REQUESTED', "So'ralgan"), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('DONE', 'Pul qaytarilgan')], db_index=True, default='REQUESTED', max_length=10, verbose_name='holat')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='qaror vaqti')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_decisions', to=settings.AUTH_USER_MODEL, verbose_name='kim qaror qilgan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.order', verbose_name='buyurtma')),
            ],
            options={
                'verbose_name': 'pul qaytarish',
                'verbose_name_plural': 'pul qaytarishlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='payments_or_status_99bb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['provider', 'action', 'created_at'], name='payments_pa_provide_5492de_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_trans_id'), name='unique_provider_transaction'),
        ),
    ]
