# Generated by Django 5.2.17 on 2026-09-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='chegirma (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=10, verbose_name='chegirma sababi'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='chegirmasiz summa'),
        ),
    ]
